### ISSUE TITLE
Regression on Shadow build using igraph v0.5.4

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#299]
shadow is no longer compatible with igraph v0.5.4. Using the library results in this error:

```
shadow-plugin-tgen/shd-tgen-graph.c:368: undefined reference to igraph_es_incident
```

The function was added in v0.6. (thanks @jdgeddes !)

**Comment by robgjansen** [comment]
I'll have to provide an alternative implementation if the function is not available.

**Comment by jdgeddes** [comment]
I forgot to mention, the function replaced igraph_es_adj which was deprecated in v0.6.  If you still want to support 0.5.4 you can probably just have an #ifdef block around the function call based on the igraph version, or something like that.

**Comment by robgjansen** [comment]
Ahh, yes! I just found that:
https://github.com/igraph/igraph/blob/master/src/iterators.c#L902

I'll push a change soon and hopefully you can test to make sure it builds correctly with 0.5.4.

**Comment by robgjansen** [comment]
@jdgeddes please let me know if this build correctly using igraph v0.5.4. (It works fine for me here using v0.6.5.)

**Comment by robgjansen** [comment]
The choose action will be removed in a345344090e73bde21998b48f9da1f1377f2c971 and so this issue will no longer apply anymore in starting in shadow version 1.11.1.
